runtime: python39

handlers:
# - url: /static
#   static_dir: static/
#   secure: always
- url: /.*
  script: auto
  # http_headers:
    # Access-Control-Allow-Origin: '*'
  secure: always

entrypoint: gunicorn -b :$PORT eabuilders.wsgi