# Generated by Django 3.1.5 on 2021-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(unique=True)),
                ('race_img', models.ImageField(upload_to='')),
                ('race_name', models.CharField(max_length=150, unique=True)),
                ('race_bonus_1', models.CharField(max_length=1000)),
                ('race_bonus_2', models.CharField(max_length=1000)),
                ('race_bonus_3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemsModel',
            new_name='ItemModel',
        ),
        migrations.RenameModel(
            old_name='RacesModel',
            new_name='MaterialModel',
        ),
        migrations.RenameField(
            model_name='materialmodel',
            old_name='race_bonus_1',
            new_name='material_bonus_1',
        ),
        migrations.RenameField(
            model_name='materialmodel',
            old_name='race_bonus_2',
            new_name='material_bonus_2',
        ),
        migrations.RenameField(
            model_name='materialmodel',
            old_name='race_bonus_3',
            new_name='material_bonus_3',
        ),
        migrations.RenameField(
            model_name='materialmodel',
            old_name='race_id',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='materialmodel',
            old_name='race_img',
            new_name='material_img',
        ),
        migrations.RenameField(
            model_name='materialmodel',
            old_name='race_name',
            new_name='material_name',
        ),
    ]
