# Generated by Django 3.1.5 on 2021-01-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210118_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.materialmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item_race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.racemodel'),
            preserve_default=False,
        ),
    ]
