# Generated by Django 3.1.5 on 2021-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210118_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmodel',
            name='material_bonus_3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='racemodel',
            name='race_bonus_3',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
