# Generated by Django 3.1.5 on 2021-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210118_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_sell_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialmodel',
            name='material_bonus_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='racemodel',
            name='race_bonus_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
